<?php namespace Neuber\Widgets\FormWidgets;

use Backend\Classes\FormWidgetBase;

/**
 * Picker Form Widget
 */
class IconPicker extends FormWidgetBase
{
    /**
     * @inheritDoc
     */
    protected $defaultAlias = 'iconpicker';

    /**
     * @inheritDoc
     */
    /* public function init(){
    } */

    /**
     * @inheritDoc
     */
    public function render()
    {
        $this->prepareVars();
        return $this->makePartial('iconpicker');
    }

    /**
     * Prepares the form widget view data
     */
    public function prepareVars()
    {
        $this->vars['icons'] = $this->getIconsList();
        $this->vars['name'] = $this->formField->getName();
        $this->vars['value'] = $this->getLoadValue();
        $this->vars['model'] = $this->model;
    }

    /**
     * @inheritDoc
     */
    public function loadAssets()
    {
        //$this->addCss('css/picker.css', 'Neuber.IconPicker');
        //$this->addJs('js/picker.js', 'Neuber.IconPicker');
    }

    /**
     * @inheritDoc
     */
    public function getSaveValue($value)
    {
        return $value;
    }
    
    
    protected function getIconsList(){
        return [
            'icon-address-book'=>'<i class="icon-address-book"></i> Address Book',
            'icon-address-book-outline'=>'<i class="icon-address-book-o"></i> Address Book Outline',
            'icon-address-card'=>'<i class="icon-address-card"></i> Address Card',
            'icon-address-card-outline'=>'<i class="icon-address-card-o"></i> Address Card Outline',
            'icon-adjust'=>'<i class="icon-adjust"></i> Adjust',
            'icon-american-sign-language-interpreting'=>'<i class="icon-american-sign-language-interpreting"></i> American Sign Language Interpreting',
            'icon-anchor'=>'<i class="icon-anchor"></i> Anchor',
            'icon-archive'=>'<i class="icon-archive"></i> Archive',
            'icon-area-chart'=>'<i class="icon-area-chart"></i> Area Chart',
            'icon-arrows'=>'<i class="icon-arrows"></i> Arrows',
            'icon-arrows-h'=>'<i class="icon-arrows-h"></i> Arrows H',
            'icon-arrows-v'=>'<i class="icon-arrows-v"></i> Arrows V',
            'icon-assistive-listening-systems'=>'<i class="icon-assistive-listening-systems"></i> Assistive Listening Systems',
            'icon-asterisk'=>'<i class="icon-asterisk"></i> Asterisk',
            'icon-at'=>'<i class="icon-at"></i> At',
            'icon-audio-description'=>'<i class="icon-audio-description"></i> Audio Description',
            'icon-balance-scale'=>'<i class="icon-balance-scale"></i> Balance Scale',
            'icon-ban'=>'<i class="icon-ban"></i> Ban',
            'icon-bar-chart'=>'<i class="icon-bar-chart"></i> Bar Chart',
            'icon-barcode'=>'<i class="icon-barcode"></i> Barcode',
            'icon-bars'=>'<i class="icon-bars"></i> Bars',
            'icon-bath'=>'<i class="icon-bath"></i> Bath',
            'icon-battery-empty'=>'<i class="icon-battery-empty"></i> Battery Empty',
            'icon-battery-full'=>'<i class="icon-battery-full"></i> Battery Full',
            'icon-battery-half'=>'<i class="icon-battery-half"></i> Battery Half',
            'icon-battery-quarter'=>'<i class="icon-battery-quarter"></i> Battery Quarter',
            'icon-battery-three-quarters'=>'<i class="icon-battery-three-quarters"></i> Battery Three Quarters',
            'icon-bed'=>'<i class="icon-bed"></i> Bed',
            'icon-beer'=>'<i class="icon-beer"></i> Beer',
            'icon-bell'=>'<i class="icon-bell"></i> Bell',
            'icon-bell-outline'=>'<i class="icon-bell-o"></i> Bell Outline',
            'icon-bell-slash'=>'<i class="icon-bell-slash"></i> Bell Slash',
            'icon-bell-slash-outline'=>'<i class="icon-bell-slash-o"></i> Bell Slash Outline',
            'icon-bicycle'=>'<i class="icon-bicycle"></i> Bicycle',
            'icon-binoculars'=>'<i class="icon-binoculars"></i> Binoculars',
            'icon-birthday-cake'=>'<i class="icon-birthday-cake"></i> Birthday Cake',
            'icon-blind'=>'<i class="icon-blind"></i> Blind',
            'icon-bluetooth'=>'<i class="icon-bluetooth"></i> Bluetooth',
            'icon-bluetooth-b'=>'<i class="icon-bluetooth-b"></i> Bluetooth B',
            'icon-bolt'=>'<i class="icon-bolt"></i> Bolt',
            'icon-bomb'=>'<i class="icon-bomb"></i> Bomb',
            'icon-book'=>'<i class="icon-book"></i> Book',
            'icon-bookmark'=>'<i class="icon-bookmark"></i> Bookmark',
            'icon-bookmark-outline'=>'<i class="icon-bookmark-o"></i> Bookmark Outline',
            'icon-braille'=>'<i class="icon-braille"></i> Braille',
            'icon-briefcase'=>'<i class="icon-briefcase"></i> Briefcase',
            'icon-bug'=>'<i class="icon-bug"></i> Bug',
            'icon-building'=>'<i class="icon-building"></i> Building',
            'icon-building-outline'=>'<i class="icon-building-o"></i> Building Outline',
            'icon-bullhorn'=>'<i class="icon-bullhorn"></i> Bullhorn',
            'icon-bullseye'=>'<i class="icon-bullseye"></i> Bullseye',
            'icon-bus'=>'<i class="icon-bus"></i> Bus',
            'icon-calculator'=>'<i class="icon-calculator"></i> Calculator',
            'icon-calendar'=>'<i class="icon-calendar"></i> Calendar',
            'icon-calendar-check-outline'=>'<i class="icon-calendar-check-o"></i> Calendar Check Outline',
            'icon-calendar-minus-outline'=>'<i class="icon-calendar-minus-o"></i> Calendar Minus Outline',
            'icon-calendar-outline'=>'<i class="icon-calendar-o"></i> Calendar Outline',
            'icon-calendar-plus-outline'=>'<i class="icon-calendar-plus-o"></i> Calendar Plus Outline',
            'icon-calendar-times-outline'=>'<i class="icon-calendar-times-o"></i> Calendar Times Outline',
            'icon-camera'=>'<i class="icon-camera"></i> Camera',
            'icon-camera-retro'=>'<i class="icon-camera-retro"></i> Camera Retro',
            'icon-car'=>'<i class="icon-car"></i> Car',
            'icon-caret-square-o-down'=>'<i class="icon-caret-square-o-down"></i> Caret Square O Down',
            'icon-caret-square-o-left'=>'<i class="icon-caret-square-o-left"></i> Caret Square O Left',
            'icon-caret-square-o-right'=>'<i class="icon-caret-square-o-right"></i> Caret Square O Right',
            'icon-caret-square-o-up'=>'<i class="icon-caret-square-o-up"></i> Caret Square O Up',
            'icon-cart-arrow-down'=>'<i class="icon-cart-arrow-down"></i> Cart Arrow Down',
            'icon-cart-plus'=>'<i class="icon-cart-plus"></i> Cart Plus',
            'icon-cc'=>'<i class="icon-cc"></i> Cc',
            'icon-certificate'=>'<i class="icon-certificate"></i> Certificate',
            'icon-check'=>'<i class="icon-check"></i> Check',
            'icon-check-circle'=>'<i class="icon-check-circle"></i> Check Circle',
            'icon-check-circle-outline'=>'<i class="icon-check-circle-o"></i> Check Circle Outline',
            'icon-check-square'=>'<i class="icon-check-square"></i> Check Square',
            'icon-check-square-outline'=>'<i class="icon-check-square-o"></i> Check Square Outline',
            'icon-child'=>'<i class="icon-child"></i> Child',
            'icon-circle'=>'<i class="icon-circle"></i> Circle',
            'icon-circle-outline'=>'<i class="icon-circle-o"></i> Circle Outline',
            'icon-circle-o-notch'=>'<i class="icon-circle-o-notch"></i> Circle O Notch',
            'icon-circle-thin'=>'<i class="icon-circle-thin"></i> Circle Thin',
            'icon-clock-outline'=>'<i class="icon-clock-o"></i> Clock Outline',
            'icon-clone'=>'<i class="icon-clone"></i> Clone',
            'icon-cloud'=>'<i class="icon-cloud"></i> Cloud',
            'icon-cloud-download'=>'<i class="icon-cloud-download"></i> Cloud Download',
            'icon-cloud-upload'=>'<i class="icon-cloud-upload"></i> Cloud Upload',
            'icon-code'=>'<i class="icon-code"></i> Code',
            'icon-code-fork'=>'<i class="icon-code-fork"></i> Code Fork',
            'icon-coffee'=>'<i class="icon-coffee"></i> Coffee',
            'icon-cog'=>'<i class="icon-cog"></i> Cog',
            'icon-cogs'=>'<i class="icon-cogs"></i> Cogs',
            'icon-comment'=>'<i class="icon-comment"></i> Comment',
            'icon-comment-outline'=>'<i class="icon-comment-o"></i> Comment Outline',
            'icon-commenting'=>'<i class="icon-commenting"></i> Commenting',
            'icon-commenting-outline'=>'<i class="icon-commenting-o"></i> Commenting Outline',
            'icon-comments'=>'<i class="icon-comments"></i> Comments',
            'icon-comments-outline'=>'<i class="icon-comments-o"></i> Comments Outline',
            'icon-compass'=>'<i class="icon-compass"></i> Compass',
            'icon-copyright'=>'<i class="icon-copyright"></i> Copyright',
            'icon-creative-commons'=>'<i class="icon-creative-commons"></i> Creative Commons',
            'icon-credit-card'=>'<i class="icon-credit-card"></i> Credit Card',
            'icon-credit-card-alt'=>'<i class="icon-credit-card-alt"></i> Credit Card Alt',
            'icon-crop'=>'<i class="icon-crop"></i> Crop',
            'icon-crosshairs'=>'<i class="icon-crosshairs"></i> Crosshairs',
            'icon-cube'=>'<i class="icon-cube"></i> Cube',
            'icon-cubes'=>'<i class="icon-cubes"></i> Cubes',
            'icon-cutlery'=>'<i class="icon-cutlery"></i> Cutlery',
            'icon-database'=>'<i class="icon-database"></i> Database',
            'icon-deaf'=>'<i class="icon-deaf"></i> Deaf',
            'icon-desktop'=>'<i class="icon-desktop"></i> Desktop',
            'icon-diamond'=>'<i class="icon-diamond"></i> Diamond',
            'icon-dot-circle-outline'=>'<i class="icon-dot-circle-o"></i> Dot Circle Outline',
            'icon-download'=>'<i class="icon-download"></i> Download',
            'icon-ellipsis-h'=>'<i class="icon-ellipsis-h"></i> Ellipsis H',
            'icon-ellipsis-v'=>'<i class="icon-ellipsis-v"></i> Ellipsis V',
            'icon-envelope'=>'<i class="icon-envelope"></i> Envelope',
            'icon-envelope-outline'=>'<i class="icon-envelope-o"></i> Envelope Outline',
            'icon-envelope-open'=>'<i class="icon-envelope-open"></i> Envelope Open',
            'icon-envelope-open-outline'=>'<i class="icon-envelope-open-o"></i> Envelope Open Outline',
            'icon-envelope-square'=>'<i class="icon-envelope-square"></i> Envelope Square',
            'icon-eraser'=>'<i class="icon-eraser"></i> Eraser',
            'icon-exchange'=>'<i class="icon-exchange"></i> Exchange',
            'icon-exclamation'=>'<i class="icon-exclamation"></i> Exclamation',
            'icon-exclamation-circle'=>'<i class="icon-exclamation-circle"></i> Exclamation Circle',
            'icon-exclamation-triangle'=>'<i class="icon-exclamation-triangle"></i> Exclamation Triangle',
            'icon-external-link'=>'<i class="icon-external-link"></i> External Link',
            'icon-external-link-square'=>'<i class="icon-external-link-square"></i> External Link Square',
            'icon-eye'=>'<i class="icon-eye"></i> Eye',
            'icon-eye-slash'=>'<i class="icon-eye-slash"></i> Eye Slash',
            'icon-eyedropper'=>'<i class="icon-eyedropper"></i> Eyedropper',
            'icon-fax'=>'<i class="icon-fax"></i> Fax',
            'icon-female'=>'<i class="icon-female"></i> Female',
            'icon-fighter-jet'=>'<i class="icon-fighter-jet"></i> Fighter Jet',
            'icon-file-archive-outline'=>'<i class="icon-file-archive-o"></i> File Archive Outline',
            'icon-file-audio-outline'=>'<i class="icon-file-audio-o"></i> File Audio Outline',
            'icon-file-code-outline'=>'<i class="icon-file-code-o"></i> File Code Outline',
            'icon-file-excel-outline'=>'<i class="icon-file-excel-o"></i> File Excel Outline',
            'icon-file-image-outline'=>'<i class="icon-file-image-o"></i> File Image Outline',
            'icon-file-pdf-outline'=>'<i class="icon-file-pdf-o"></i> File Pdf Outline',
            'icon-file-powerpoint-outline'=>'<i class="icon-file-powerpoint-o"></i> File Powerpoint Outline',
            'icon-file-video-outline'=>'<i class="icon-file-video-o"></i> File Video Outline',
            'icon-file-word-outline'=>'<i class="icon-file-word-o"></i> File Word Outline',
            'icon-film'=>'<i class="icon-film"></i> Film',
            'icon-filter'=>'<i class="icon-filter"></i> Filter',
            'icon-fire'=>'<i class="icon-fire"></i> Fire',
            'icon-fire-extinguisher'=>'<i class="icon-fire-extinguisher"></i> Fire Extinguisher',
            'icon-flag'=>'<i class="icon-flag"></i> Flag',
            'icon-flag-checkered'=>'<i class="icon-flag-checkered"></i> Flag Checkered',
            'icon-flag-outline'=>'<i class="icon-flag-o"></i> Flag Outline',
            'icon-flask'=>'<i class="icon-flask"></i> Flask',
            'icon-folder'=>'<i class="icon-folder"></i> Folder',
            'icon-folder-outline'=>'<i class="icon-folder-o"></i> Folder Outline',
            'icon-folder-open'=>'<i class="icon-folder-open"></i> Folder Open',
            'icon-folder-open-outline'=>'<i class="icon-folder-open-o"></i> Folder Open Outline',
            'icon-frown-outline'=>'<i class="icon-frown-o"></i> Frown Outline',
            'icon-futbol-outline'=>'<i class="icon-futbol-o"></i> Futbol Outline',
            'icon-gamepad'=>'<i class="icon-gamepad"></i> Gamepad',
            'icon-gavel'=>'<i class="icon-gavel"></i> Gavel',
            'icon-gift'=>'<i class="icon-gift"></i> Gift',
            'icon-glass'=>'<i class="icon-glass"></i> Glass',
            'icon-globe'=>'<i class="icon-globe"></i> Globe',
            'icon-graduation-cap'=>'<i class="icon-graduation-cap"></i> Graduation Cap',
            'icon-hand-lizard-outline'=>'<i class="icon-hand-lizard-o"></i> Hand Lizard Outline',
            'icon-hand-paper-outline'=>'<i class="icon-hand-paper-o"></i> Hand Paper Outline',
            'icon-hand-peace-outline'=>'<i class="icon-hand-peace-o"></i> Hand Peace Outline',
            'icon-hand-pointer-outline'=>'<i class="icon-hand-pointer-o"></i> Hand Pointer Outline',
            'icon-hand-rock-outline'=>'<i class="icon-hand-rock-o"></i> Hand Rock Outline',
            'icon-hand-scissors-outline'=>'<i class="icon-hand-scissors-o"></i> Hand Scissors Outline',
            'icon-hand-spock-outline'=>'<i class="icon-hand-spock-o"></i> Hand Spock Outline',
            'icon-handshake-outline'=>'<i class="icon-handshake-o"></i> Handshake Outline',
            'icon-hashtag'=>'<i class="icon-hashtag"></i> Hashtag',
            'icon-hdd-outline'=>'<i class="icon-hdd-o"></i> Hdd Outline',
            'icon-headphones'=>'<i class="icon-headphones"></i> Headphones',
            'icon-heart'=>'<i class="icon-heart"></i> Heart',
            'icon-heart-outline'=>'<i class="icon-heart-o"></i> Heart Outline',
            'icon-heartbeat'=>'<i class="icon-heartbeat"></i> Heartbeat',
            'icon-history'=>'<i class="icon-history"></i> History',
            'icon-home'=>'<i class="icon-home"></i> Home',
            'icon-hourglass'=>'<i class="icon-hourglass"></i> Hourglass',
            'icon-hourglass-end'=>'<i class="icon-hourglass-end"></i> Hourglass End',
            'icon-hourglass-half'=>'<i class="icon-hourglass-half"></i> Hourglass Half',
            'icon-hourglass-outline'=>'<i class="icon-hourglass-o"></i> Hourglass Outline',
            'icon-hourglass-start'=>'<i class="icon-hourglass-start"></i> Hourglass Start',
            'icon-i-cursor'=>'<i class="icon-i-cursor"></i> I Cursor',
            'icon-id-badge'=>'<i class="icon-id-badge"></i> Id Badge',
            'icon-id-card'=>'<i class="icon-id-card"></i> Id Card',
            'icon-id-card-outline'=>'<i class="icon-id-card-o"></i> Id Card Outline',
            'icon-inbox'=>'<i class="icon-inbox"></i> Inbox',
            'icon-industry'=>'<i class="icon-industry"></i> Industry',
            'icon-info'=>'<i class="icon-info"></i> Info',
            'icon-info-circle'=>'<i class="icon-info-circle"></i> Info Circle',
            'icon-key'=>'<i class="icon-key"></i> Key',
            'icon-keyboard-outline'=>'<i class="icon-keyboard-o"></i> Keyboard Outline',
            'icon-language'=>'<i class="icon-language"></i> Language',
            'icon-laptop'=>'<i class="icon-laptop"></i> Laptop',
            'icon-leaf'=>'<i class="icon-leaf"></i> Leaf',
            'icon-lemon-outline'=>'<i class="icon-lemon-o"></i> Lemon Outline',
            'icon-level-down'=>'<i class="icon-level-down"></i> Level Down',
            'icon-level-up'=>'<i class="icon-level-up"></i> Level Up',
            'icon-life-ring'=>'<i class="icon-life-ring"></i> Life Ring',
            'icon-lightbulb-outline'=>'<i class="icon-lightbulb-o"></i> Lightbulb Outline',
            'icon-line-chart'=>'<i class="icon-line-chart"></i> Line Chart',
            'icon-location-arrow'=>'<i class="icon-location-arrow"></i> Location Arrow',
            'icon-lock'=>'<i class="icon-lock"></i> Lock',
            'icon-low-vision'=>'<i class="icon-low-vision"></i> Low Vision',
            'icon-magic'=>'<i class="icon-magic"></i> Magic',
            'icon-magnet'=>'<i class="icon-magnet"></i> Magnet',
            'icon-male'=>'<i class="icon-male"></i> Male',
            'icon-map'=>'<i class="icon-map"></i> Map',
            'icon-map-marker'=>'<i class="icon-map-marker"></i> Map Marker',
            'icon-map-outline'=>'<i class="icon-map-o"></i> Map Outline',
            'icon-map-pin'=>'<i class="icon-map-pin"></i> Map Pin',
            'icon-map-signs'=>'<i class="icon-map-signs"></i> Map Signs',
            'icon-meh-outline'=>'<i class="icon-meh-o"></i> Meh Outline',
            'icon-microchip'=>'<i class="icon-microchip"></i> Microchip',
            'icon-microphone'=>'<i class="icon-microphone"></i> Microphone',
            'icon-microphone-slash'=>'<i class="icon-microphone-slash"></i> Microphone Slash',
            'icon-minus'=>'<i class="icon-minus"></i> Minus',
            'icon-minus-circle'=>'<i class="icon-minus-circle"></i> Minus Circle',
            'icon-minus-square'=>'<i class="icon-minus-square"></i> Minus Square',
            'icon-minus-square-outline'=>'<i class="icon-minus-square-o"></i> Minus Square Outline',
            'icon-mobile'=>'<i class="icon-mobile"></i> Mobile',
            'icon-money'=>'<i class="icon-money"></i> Money',
            'icon-moon-outline'=>'<i class="icon-moon-o"></i> Moon Outline',
            'icon-motorcycle'=>'<i class="icon-motorcycle"></i> Motorcycle',
            'icon-mouse-pointer'=>'<i class="icon-mouse-pointer"></i> Mouse Pointer',
            'icon-music'=>'<i class="icon-music"></i> Music',
            'icon-newspaper-outline'=>'<i class="icon-newspaper-o"></i> Newspaper Outline',
            'icon-object-group'=>'<i class="icon-object-group"></i> Object Group',
            'icon-object-ungroup'=>'<i class="icon-object-ungroup"></i> Object Ungroup',
            'icon-paint-brush'=>'<i class="icon-paint-brush"></i> Paint Brush',
            'icon-paper-plane'=>'<i class="icon-paper-plane"></i> Paper Plane',
            'icon-paper-plane-outline'=>'<i class="icon-paper-plane-o"></i> Paper Plane Outline',
            'icon-paw'=>'<i class="icon-paw"></i> Paw',
            'icon-pencil'=>'<i class="icon-pencil"></i> Pencil',
            'icon-pencil-square'=>'<i class="icon-pencil-square"></i> Pencil Square',
            'icon-pencil-square-outline'=>'<i class="icon-pencil-square-o"></i> Pencil Square Outline',
            'icon-percent'=>'<i class="icon-percent"></i> Percent',
            'icon-phone'=>'<i class="icon-phone"></i> Phone',
            'icon-phone-square'=>'<i class="icon-phone-square"></i> Phone Square',
            'icon-picture-outline'=>'<i class="icon-picture-o"></i> Picture Outline',
            'icon-pie-chart'=>'<i class="icon-pie-chart"></i> Pie Chart',
            'icon-plane'=>'<i class="icon-plane"></i> Plane',
            'icon-plug'=>'<i class="icon-plug"></i> Plug',
            'icon-plus'=>'<i class="icon-plus"></i> Plus',
            'icon-plus-circle'=>'<i class="icon-plus-circle"></i> Plus Circle',
            'icon-plus-square'=>'<i class="icon-plus-square"></i> Plus Square',
            'icon-plus-square-outline'=>'<i class="icon-plus-square-o"></i> Plus Square Outline',
            'icon-podcast'=>'<i class="icon-podcast"></i> Podcast',
            'icon-power-off'=>'<i class="icon-power-off"></i> Power Off',
            'icon-print'=>'<i class="icon-print"></i> Print',
            'icon-puzzle-piece'=>'<i class="icon-puzzle-piece"></i> Puzzle Piece',
            'icon-qrcode'=>'<i class="icon-qrcode"></i> Qrcode',
            'icon-question'=>'<i class="icon-question"></i> Question',
            'icon-question-circle'=>'<i class="icon-question-circle"></i> Question Circle',
            'icon-question-circle-outline'=>'<i class="icon-question-circle-o"></i> Question Circle Outline',
            'icon-quote-left'=>'<i class="icon-quote-left"></i> Quote Left',
            'icon-quote-right'=>'<i class="icon-quote-right"></i> Quote Right',
            'icon-random'=>'<i class="icon-random"></i> Random',
            'icon-recycle'=>'<i class="icon-recycle"></i> Recycle',
            'icon-refresh'=>'<i class="icon-refresh"></i> Refresh',
            'icon-registered'=>'<i class="icon-registered"></i> Registered',
            'icon-reply'=>'<i class="icon-reply"></i> Reply',
            'icon-reply-all'=>'<i class="icon-reply-all"></i> Reply All',
            'icon-retweet'=>'<i class="icon-retweet"></i> Retweet',
            'icon-road'=>'<i class="icon-road"></i> Road',
            'icon-rocket'=>'<i class="icon-rocket"></i> Rocket',
            'icon-rss'=>'<i class="icon-rss"></i> Rss',
            'icon-rss-square'=>'<i class="icon-rss-square"></i> Rss Square',
            'icon-search'=>'<i class="icon-search"></i> Search',
            'icon-search-minus'=>'<i class="icon-search-minus"></i> Search Minus',
            'icon-search-plus'=>'<i class="icon-search-plus"></i> Search Plus',
            'icon-server'=>'<i class="icon-server"></i> Server',
            'icon-share'=>'<i class="icon-share"></i> Share',
            'icon-share-alt'=>'<i class="icon-share-alt"></i> Share Alt',
            'icon-share-alt-square'=>'<i class="icon-share-alt-square"></i> Share Alt Square',
            'icon-share-square'=>'<i class="icon-share-square"></i> Share Square',
            'icon-share-square-outline'=>'<i class="icon-share-square-o"></i> Share Square Outline',
            'icon-shield'=>'<i class="icon-shield"></i> Shield',
            'icon-ship'=>'<i class="icon-ship"></i> Ship',
            'icon-shopping-bag'=>'<i class="icon-shopping-bag"></i> Shopping Bag',
            'icon-shopping-basket'=>'<i class="icon-shopping-basket"></i> Shopping Basket',
            'icon-shopping-cart'=>'<i class="icon-shopping-cart"></i> Shopping Cart',
            'icon-shower'=>'<i class="icon-shower"></i> Shower',
            'icon-sign-in'=>'<i class="icon-sign-in"></i> Sign In',
            'icon-sign-language'=>'<i class="icon-sign-language"></i> Sign Language',
            'icon-sign-out'=>'<i class="icon-sign-out"></i> Sign Out',
            'icon-signal'=>'<i class="icon-signal"></i> Signal',
            'icon-sitemap'=>'<i class="icon-sitemap"></i> Sitemap',
            'icon-sliders'=>'<i class="icon-sliders"></i> Sliders',
            'icon-smile-outline'=>'<i class="icon-smile-o"></i> Smile Outline',
            'icon-snowflake-outline'=>'<i class="icon-snowflake-o"></i> Snowflake Outline',
            'icon-sort'=>'<i class="icon-sort"></i> Sort',
            'icon-sort-alpha-asc'=>'<i class="icon-sort-alpha-asc"></i> Sort Alpha Asc',
            'icon-sort-alpha-desc'=>'<i class="icon-sort-alpha-desc"></i> Sort Alpha Desc',
            'icon-sort-amount-asc'=>'<i class="icon-sort-amount-asc"></i> Sort Amount Asc',
            'icon-sort-amount-desc'=>'<i class="icon-sort-amount-desc"></i> Sort Amount Desc',
            'icon-sort-asc'=>'<i class="icon-sort-asc"></i> Sort Asc',
            'icon-sort-desc'=>'<i class="icon-sort-desc"></i> Sort Desc',
            'icon-sort-numeric-asc'=>'<i class="icon-sort-numeric-asc"></i> Sort Numeric Asc',
            'icon-sort-numeric-desc'=>'<i class="icon-sort-numeric-desc"></i> Sort Numeric Desc',
            'icon-space-shuttle'=>'<i class="icon-space-shuttle"></i> Space Shuttle',
            'icon-spinner'=>'<i class="icon-spinner"></i> Spinner',
            'icon-spoon'=>'<i class="icon-spoon"></i> Spoon',
            'icon-square'=>'<i class="icon-square"></i> Square',
            'icon-square-outline'=>'<i class="icon-square-o"></i> Square Outline',
            'icon-star'=>'<i class="icon-star"></i> Star',
            'icon-star-half'=>'<i class="icon-star-half"></i> Star Half',
            'icon-star-half-outline'=>'<i class="icon-star-half-o"></i> Star Half Outline',
            'icon-star-outline'=>'<i class="icon-star-o"></i> Star Outline',
            'icon-sticky-note'=>'<i class="icon-sticky-note"></i> Sticky Note',
            'icon-sticky-note-outline'=>'<i class="icon-sticky-note-o"></i> Sticky Note Outline',
            'icon-street-view'=>'<i class="icon-street-view"></i> Street View',
            'icon-suitcase'=>'<i class="icon-suitcase"></i> Suitcase',
            'icon-sun-outline'=>'<i class="icon-sun-o"></i> Sun Outline',
            'icon-tablet'=>'<i class="icon-tablet"></i> Tablet',
            'icon-tachometer'=>'<i class="icon-tachometer"></i> Tachometer',
            'icon-tag'=>'<i class="icon-tag"></i> Tag',
            'icon-tags'=>'<i class="icon-tags"></i> Tags',
            'icon-tasks'=>'<i class="icon-tasks"></i> Tasks',
            'icon-taxi'=>'<i class="icon-taxi"></i> Taxi',
            'icon-television'=>'<i class="icon-television"></i> Television',
            'icon-terminal'=>'<i class="icon-terminal"></i> Terminal',
            'icon-thermometer-empty'=>'<i class="icon-thermometer-empty"></i> Thermometer Empty',
            'icon-thermometer-full'=>'<i class="icon-thermometer-full"></i> Thermometer Full',
            'icon-thermometer-half'=>'<i class="icon-thermometer-half"></i> Thermometer Half',
            'icon-thermometer-quarter'=>'<i class="icon-thermometer-quarter"></i> Thermometer Quarter',
            'icon-thermometer-three-quarters'=>'<i class="icon-thermometer-three-quarters"></i> Thermometer Three Quarters',
            'icon-thumb-tack'=>'<i class="icon-thumb-tack"></i> Thumb Tack',
            'icon-thumbs-down'=>'<i class="icon-thumbs-down"></i> Thumbs Down',
            'icon-thumbs-o-down'=>'<i class="icon-thumbs-o-down"></i> Thumbs O Down',
            'icon-thumbs-o-up'=>'<i class="icon-thumbs-o-up"></i> Thumbs O Up',
            'icon-thumbs-up'=>'<i class="icon-thumbs-up"></i> Thumbs Up',
            'icon-ticket'=>'<i class="icon-ticket"></i> Ticket',
            'icon-times'=>'<i class="icon-times"></i> Times',
            'icon-times-circle'=>'<i class="icon-times-circle"></i> Times Circle',
            'icon-times-circle-outline'=>'<i class="icon-times-circle-o"></i> Times Circle Outline',
            'icon-tint'=>'<i class="icon-tint"></i> Tint',
            'icon-toggle-off'=>'<i class="icon-toggle-off"></i> Toggle Off',
            'icon-toggle-on'=>'<i class="icon-toggle-on"></i> Toggle On',
            'icon-trademark'=>'<i class="icon-trademark"></i> Trademark',
            'icon-trash'=>'<i class="icon-trash"></i> Trash',
            'icon-trash-outline'=>'<i class="icon-trash-o"></i> Trash Outline',
            'icon-tree'=>'<i class="icon-tree"></i> Tree',
            'icon-trophy'=>'<i class="icon-trophy"></i> Trophy',
            'icon-truck'=>'<i class="icon-truck"></i> Truck',
            'icon-tty'=>'<i class="icon-tty"></i> Tty',
            'icon-umbrella'=>'<i class="icon-umbrella"></i> Umbrella',
            'icon-universal-access'=>'<i class="icon-universal-access"></i> Universal Access',
            'icon-university'=>'<i class="icon-university"></i> University',
            'icon-unlock'=>'<i class="icon-unlock"></i> Unlock',
            'icon-unlock-alt'=>'<i class="icon-unlock-alt"></i> Unlock Alt',
            'icon-upload'=>'<i class="icon-upload"></i> Upload',
            'icon-user'=>'<i class="icon-user"></i> User',
            'icon-user-circle'=>'<i class="icon-user-circle"></i> User Circle',
            'icon-user-circle-outline'=>'<i class="icon-user-circle-o"></i> User Circle Outline',
            'icon-user-outline'=>'<i class="icon-user-o"></i> User Outline',
            'icon-user-plus'=>'<i class="icon-user-plus"></i> User Plus',
            'icon-user-secret'=>'<i class="icon-user-secret"></i> User Secret',
            'icon-user-times'=>'<i class="icon-user-times"></i> User Times',
            'icon-users'=>'<i class="icon-users"></i> Users',
            'icon-video-camera'=>'<i class="icon-video-camera"></i> Video Camera',
            'icon-volume-control-phone'=>'<i class="icon-volume-control-phone"></i> Volume Control Phone',
            'icon-volume-down'=>'<i class="icon-volume-down"></i> Volume Down',
            'icon-volume-off'=>'<i class="icon-volume-off"></i> Volume Off',
            'icon-volume-up'=>'<i class="icon-volume-up"></i> Volume Up',
            'icon-wheelchair'=>'<i class="icon-wheelchair"></i> Wheelchair',
            'icon-wheelchair-alt'=>'<i class="icon-wheelchair-alt"></i> Wheelchair Alt',
            'icon-wifi'=>'<i class="icon-wifi"></i> Wifi',
            'icon-window-close'=>'<i class="icon-window-close"></i> Window Close',
            'icon-window-close-outline'=>'<i class="icon-window-close-o"></i> Window Close Outline',
            'icon-window-maximize'=>'<i class="icon-window-maximize"></i> Window Maximize',
            'icon-window-minimize'=>'<i class="icon-window-minimize"></i> Window Minimize',
            'icon-window-restore'=>'<i class="icon-window-restore"></i> Window Restore',
            'icon-wrench'=>'<i class="icon-wrench"></i> Wrench',
            'icon-ambulance'=>'<i class="icon-ambulance"></i> Ambulance',
            'icon-h-square'=>'<i class="icon-h-square"></i> H Square',
            'icon-heart'=>'<i class="icon-heart"></i> Heart',
            'icon-heart-outline'=>'<i class="icon-heart-o"></i> Heart Outline',
            'icon-heartbeat'=>'<i class="icon-heartbeat"></i> Heartbeat',
            'icon-hospital-outline'=>'<i class="icon-hospital-o"></i> Hospital Outline',
            'icon-medkit'=>'<i class="icon-medkit"></i> Medkit',
            'icon-plus-square'=>'<i class="icon-plus-square"></i> Plus Square',
            'icon-stethoscope'=>'<i class="icon-stethoscope"></i> Stethoscope',
            'icon-user-md'=>'<i class="icon-user-md"></i> User Md',
            'icon-wheelchair'=>'<i class="icon-wheelchair"></i> Wheelchair',
            'icon-wheelchair-alt'=>'<i class="icon-wheelchair-alt"></i> Wheelchair Alt',
            'icon-align-center'=>'<i class="icon-align-center"></i> Align Center',
            'icon-align-justify'=>'<i class="icon-align-justify"></i> Align Justify',
            'icon-align-left'=>'<i class="icon-align-left"></i> Align Left',
            'icon-align-right'=>'<i class="icon-align-right"></i> Align Right',
            'icon-bold'=>'<i class="icon-bold"></i> Bold',
            'icon-chain-broken'=>'<i class="icon-chain-broken"></i> Chain Broken',
            'icon-clipboard'=>'<i class="icon-clipboard"></i> Clipboard',
            'icon-columns'=>'<i class="icon-columns"></i> Columns',
            'icon-eraser'=>'<i class="icon-eraser"></i> Eraser',
            'icon-file'=>'<i class="icon-file"></i> File',
            'icon-file-outline'=>'<i class="icon-file-o"></i> File Outline',
            'icon-file-text'=>'<i class="icon-file-text"></i> File Text',
            'icon-file-text-outline'=>'<i class="icon-file-text-o"></i> File Text Outline',
            'icon-files-outline'=>'<i class="icon-files-o"></i> Files Outline',
            'icon-floppy-outline'=>'<i class="icon-floppy-o"></i> Floppy Outline',
            'icon-font'=>'<i class="icon-font"></i> Font',
            'icon-header'=>'<i class="icon-header"></i> Header',
            'icon-indent'=>'<i class="icon-indent"></i> Indent',
            'icon-italic'=>'<i class="icon-italic"></i> Italic',
            'icon-link'=>'<i class="icon-link"></i> Link',
            'icon-list'=>'<i class="icon-list"></i> List',
            'icon-list-alt'=>'<i class="icon-list-alt"></i> List Alt',
            'icon-list-ol'=>'<i class="icon-list-ol"></i> List Ol',
            'icon-list-ul'=>'<i class="icon-list-ul"></i> List Ul',
            'icon-outdent'=>'<i class="icon-outdent"></i> Outdent',
            'icon-paperclip'=>'<i class="icon-paperclip"></i> Paperclip',
            'icon-paragraph'=>'<i class="icon-paragraph"></i> Paragraph',
            'icon-repeat'=>'<i class="icon-repeat"></i> Repeat',
            'icon-scissors'=>'<i class="icon-scissors"></i> Scissors',
            'icon-strikethrough'=>'<i class="icon-strikethrough"></i> Strikethrough',
            'icon-subscript'=>'<i class="icon-subscript"></i> Subscript',
            'icon-superscript'=>'<i class="icon-superscript"></i> Superscript',
            'icon-table'=>'<i class="icon-table"></i> Table',
            'icon-text-height'=>'<i class="icon-text-height"></i> Text Height',
            'icon-text-width'=>'<i class="icon-text-width"></i> Text Width',
            'icon-th'=>'<i class="icon-th"></i> Th',
            'icon-th-large'=>'<i class="icon-th-large"></i> Th Large',
            'icon-th-list'=>'<i class="icon-th-list"></i> Th List',
            'icon-underline'=>'<i class="icon-underline"></i> Underline',
            'icon-undo'=>'<i class="icon-undo"></i> Undo',
            'icon-circle-o-notch'=>'<i class="icon-circle-o-notch"></i> Circle O Notch',
            'icon-cog'=>'<i class="icon-cog"></i> Cog',
            'icon-refresh'=>'<i class="icon-refresh"></i> Refresh',
            'icon-spinner'=>'<i class="icon-spinner"></i> Spinner',
            'icon-file'=>'<i class="icon-file"></i> File',
            'icon-file-archive-outline'=>'<i class="icon-file-archive-o"></i> File Archive Outline',
            'icon-file-audio-outline'=>'<i class="icon-file-audio-o"></i> File Audio Outline',
            'icon-file-code-outline'=>'<i class="icon-file-code-o"></i> File Code Outline',
            'icon-file-excel-outline'=>'<i class="icon-file-excel-o"></i> File Excel Outline',
            'icon-file-image-outline'=>'<i class="icon-file-image-o"></i> File Image Outline',
            'icon-file-outline'=>'<i class="icon-file-o"></i> File Outline',
            'icon-file-pdf-outline'=>'<i class="icon-file-pdf-o"></i> File Pdf Outline',
            'icon-file-powerpoint-outline'=>'<i class="icon-file-powerpoint-o"></i> File Powerpoint Outline',
            'icon-file-text'=>'<i class="icon-file-text"></i> File Text',
            'icon-file-text-outline'=>'<i class="icon-file-text-o"></i> File Text Outline',
            'icon-file-video-outline'=>'<i class="icon-file-video-o"></i> File Video Outline',
            'icon-file-word-outline'=>'<i class="icon-file-word-o"></i> File Word Outline',
            'icon-angle-double-down'=>'<i class="icon-angle-double-down"></i> Angle Double Down',
            'icon-angle-double-left'=>'<i class="icon-angle-double-left"></i> Angle Double Left',
            'icon-angle-double-right'=>'<i class="icon-angle-double-right"></i> Angle Double Right',
            'icon-angle-double-up'=>'<i class="icon-angle-double-up"></i> Angle Double Up',
            'icon-angle-down'=>'<i class="icon-angle-down"></i> Angle Down',
            'icon-angle-left'=>'<i class="icon-angle-left"></i> Angle Left',
            'icon-angle-right'=>'<i class="icon-angle-right"></i> Angle Right',
            'icon-angle-up'=>'<i class="icon-angle-up"></i> Angle Up',
            'icon-arrow-circle-down'=>'<i class="icon-arrow-circle-down"></i> Arrow Circle Down',
            'icon-arrow-circle-left'=>'<i class="icon-arrow-circle-left"></i> Arrow Circle Left',
            'icon-arrow-circle-o-down'=>'<i class="icon-arrow-circle-o-down"></i> Arrow Circle O Down',
            'icon-arrow-circle-o-left'=>'<i class="icon-arrow-circle-o-left"></i> Arrow Circle O Left',
            'icon-arrow-circle-o-right'=>'<i class="icon-arrow-circle-o-right"></i> Arrow Circle O Right',
            'icon-arrow-circle-o-up'=>'<i class="icon-arrow-circle-o-up"></i> Arrow Circle O Up',
            'icon-arrow-circle-right'=>'<i class="icon-arrow-circle-right"></i> Arrow Circle Right',
            'icon-arrow-circle-up'=>'<i class="icon-arrow-circle-up"></i> Arrow Circle Up',
            'icon-arrow-down'=>'<i class="icon-arrow-down"></i> Arrow Down',
            'icon-arrow-left'=>'<i class="icon-arrow-left"></i> Arrow Left',
            'icon-arrow-right'=>'<i class="icon-arrow-right"></i> Arrow Right',
            'icon-arrow-up'=>'<i class="icon-arrow-up"></i> Arrow Up',
            'icon-arrows'=>'<i class="icon-arrows"></i> Arrows',
            'icon-arrows-alt'=>'<i class="icon-arrows-alt"></i> Arrows Alt',
            'icon-arrows-h'=>'<i class="icon-arrows-h"></i> Arrows H',
            'icon-arrows-v'=>'<i class="icon-arrows-v"></i> Arrows V',
            'icon-caret-down'=>'<i class="icon-caret-down"></i> Caret Down',
            'icon-caret-left'=>'<i class="icon-caret-left"></i> Caret Left',
            'icon-caret-right'=>'<i class="icon-caret-right"></i> Caret Right',
            'icon-caret-square-o-down'=>'<i class="icon-caret-square-o-down"></i> Caret Square O Down',
            'icon-caret-square-o-left'=>'<i class="icon-caret-square-o-left"></i> Caret Square O Left',
            'icon-caret-square-o-right'=>'<i class="icon-caret-square-o-right"></i> Caret Square O Right',
            'icon-caret-square-o-up'=>'<i class="icon-caret-square-o-up"></i> Caret Square O Up',
            'icon-caret-up'=>'<i class="icon-caret-up"></i> Caret Up',
            'icon-chevron-circle-down'=>'<i class="icon-chevron-circle-down"></i> Chevron Circle Down',
            'icon-chevron-circle-left'=>'<i class="icon-chevron-circle-left"></i> Chevron Circle Left',
            'icon-chevron-circle-right'=>'<i class="icon-chevron-circle-right"></i> Chevron Circle Right',
            'icon-chevron-circle-up'=>'<i class="icon-chevron-circle-up"></i> Chevron Circle Up',
            'icon-chevron-down'=>'<i class="icon-chevron-down"></i> Chevron Down',
            'icon-chevron-left'=>'<i class="icon-chevron-left"></i> Chevron Left',
            'icon-chevron-right'=>'<i class="icon-chevron-right"></i> Chevron Right',
            'icon-chevron-up'=>'<i class="icon-chevron-up"></i> Chevron Up',
            'icon-exchange'=>'<i class="icon-exchange"></i> Exchange',
            'icon-hand-o-down'=>'<i class="icon-hand-o-down"></i> Hand O Down',
            'icon-hand-o-left'=>'<i class="icon-hand-o-left"></i> Hand O Left',
            'icon-hand-o-right'=>'<i class="icon-hand-o-right"></i> Hand O Right',
            'icon-hand-o-up'=>'<i class="icon-hand-o-up"></i> Hand O Up',
            'icon-long-arrow-down'=>'<i class="icon-long-arrow-down"></i> Long Arrow Down',
            'icon-long-arrow-left'=>'<i class="icon-long-arrow-left"></i> Long Arrow Left',
            'icon-long-arrow-right'=>'<i class="icon-long-arrow-right"></i> Long Arrow Right',
            'icon-long-arrow-up'=>'<i class="icon-long-arrow-up"></i> Long Arrow Up',
            'icon-arrows-alt'=>'<i class="icon-arrows-alt"></i> Arrows Alt',
            'icon-backward'=>'<i class="icon-backward"></i> Backward',
            'icon-compress'=>'<i class="icon-compress"></i> Compress',
            'icon-eject'=>'<i class="icon-eject"></i> Eject',
            'icon-expand'=>'<i class="icon-expand"></i> Expand',
            'icon-fast-backward'=>'<i class="icon-fast-backward"></i> Fast Backward',
            'icon-fast-forward'=>'<i class="icon-fast-forward"></i> Fast Forward',
            'icon-forward'=>'<i class="icon-forward"></i> Forward',
            'icon-pause'=>'<i class="icon-pause"></i> Pause',
            'icon-pause-circle'=>'<i class="icon-pause-circle"></i> Pause Circle',
            'icon-pause-circle-outline'=>'<i class="icon-pause-circle-o"></i> Pause Circle Outline',
            'icon-play'=>'<i class="icon-play"></i> Play',
            'icon-play-circle'=>'<i class="icon-play-circle"></i> Play Circle',
            'icon-play-circle-outline'=>'<i class="icon-play-circle-o"></i> Play Circle Outline',
            'icon-random'=>'<i class="icon-random"></i> Random',
            'icon-step-backward'=>'<i class="icon-step-backward"></i> Step Backward',
            'icon-step-forward'=>'<i class="icon-step-forward"></i> Step Forward',
            'icon-stop'=>'<i class="icon-stop"></i> Stop',
            'icon-stop-circle'=>'<i class="icon-stop-circle"></i> Stop Circle',
            'icon-stop-circle-outline'=>'<i class="icon-stop-circle-o"></i> Stop Circle Outline',
            'icon-youtube-play'=>'<i class="icon-youtube-play"></i> Youtube Play',
            'icon-check-square'=>'<i class="icon-check-square"></i> Check Square',
            'icon-check-square-outline'=>'<i class="icon-check-square-o"></i> Check Square Outline',
            'icon-circle'=>'<i class="icon-circle"></i> Circle',
            'icon-circle-outline'=>'<i class="icon-circle-o"></i> Circle Outline',
            'icon-dot-circle-outline'=>'<i class="icon-dot-circle-o"></i> Dot Circle Outline',
            'icon-minus-square'=>'<i class="icon-minus-square"></i> Minus Square',
            'icon-minus-square-outline'=>'<i class="icon-minus-square-o"></i> Minus Square Outline',
            'icon-plus-square'=>'<i class="icon-plus-square"></i> Plus Square',
            'icon-plus-square-outline'=>'<i class="icon-plus-square-o"></i> Plus Square Outline',
            'icon-square'=>'<i class="icon-square"></i> Square',
            'icon-square-outline'=>'<i class="icon-square-o"></i> Square Outline',
            'icon-ambulance'=>'<i class="icon-ambulance"></i> Ambulance',
            'icon-bicycle'=>'<i class="icon-bicycle"></i> Bicycle',
            'icon-bus'=>'<i class="icon-bus"></i> Bus',
            'icon-car'=>'<i class="icon-car"></i> Car',
            'icon-fighter-jet'=>'<i class="icon-fighter-jet"></i> Fighter Jet',
            'icon-motorcycle'=>'<i class="icon-motorcycle"></i> Motorcycle',
            'icon-plane'=>'<i class="icon-plane"></i> Plane',
            'icon-rocket'=>'<i class="icon-rocket"></i> Rocket',
            'icon-ship'=>'<i class="icon-ship"></i> Ship',
            'icon-space-shuttle'=>'<i class="icon-space-shuttle"></i> Space Shuttle',
            'icon-subway'=>'<i class="icon-subway"></i> Subway',
            'icon-taxi'=>'<i class="icon-taxi"></i> Taxi',
            'icon-train'=>'<i class="icon-train"></i> Train',
            'icon-truck'=>'<i class="icon-truck"></i> Truck',
            'icon-wheelchair'=>'<i class="icon-wheelchair"></i> Wheelchair',
            'icon-wheelchair-alt'=>'<i class="icon-wheelchair-alt"></i> Wheelchair Alt',
            'icon-area-chart'=>'<i class="icon-area-chart"></i> Area Chart',
            'icon-bar-chart'=>'<i class="icon-bar-chart"></i> Bar Chart',
            'icon-line-chart'=>'<i class="icon-line-chart"></i> Line Chart',
            'icon-pie-chart'=>'<i class="icon-pie-chart"></i> Pie Chart',
            'icon-500px'=>'<i class="icon-500px"></i> 500px',
            'icon-adn'=>'<i class="icon-adn"></i> Adn',
            'icon-amazon'=>'<i class="icon-amazon"></i> Amazon',
            'icon-android'=>'<i class="icon-android"></i> Android',
            'icon-angellist'=>'<i class="icon-angellist"></i> Angellist',
            'icon-apple'=>'<i class="icon-apple"></i> Apple',
            'icon-bandcamp'=>'<i class="icon-bandcamp"></i> Bandcamp',
            'icon-behance'=>'<i class="icon-behance"></i> Behance',
            'icon-behance-square'=>'<i class="icon-behance-square"></i> Behance Square',
            'icon-bitbucket'=>'<i class="icon-bitbucket"></i> Bitbucket',
            'icon-bitbucket-square'=>'<i class="icon-bitbucket-square"></i> Bitbucket Square',
            'icon-black-tie'=>'<i class="icon-black-tie"></i> Black Tie',
            'icon-bluetooth'=>'<i class="icon-bluetooth"></i> Bluetooth',
            'icon-bluetooth-b'=>'<i class="icon-bluetooth-b"></i> Bluetooth B',
            'icon-btc'=>'<i class="icon-btc"></i> Btc',
            'icon-buysellads'=>'<i class="icon-buysellads"></i> Buysellads',
            'icon-cc-amex'=>'<i class="icon-cc-amex"></i> Cc Amex',
            'icon-cc-diners-club'=>'<i class="icon-cc-diners-club"></i> Cc Diners Club',
            'icon-cc-discover'=>'<i class="icon-cc-discover"></i> Cc Discover',
            'icon-cc-jcb'=>'<i class="icon-cc-jcb"></i> Cc Jcb',
            'icon-cc-mastercard'=>'<i class="icon-cc-mastercard"></i> Cc Mastercard',
            'icon-cc-paypal'=>'<i class="icon-cc-paypal"></i> Cc Paypal',
            'icon-cc-stripe'=>'<i class="icon-cc-stripe"></i> Cc Stripe',
            'icon-cc-visa'=>'<i class="icon-cc-visa"></i> Cc Visa',
            'icon-chrome'=>'<i class="icon-chrome"></i> Chrome',
            'icon-codepen'=>'<i class="icon-codepen"></i> Codepen',
            'icon-codiepie'=>'<i class="icon-codiepie"></i> Codiepie',
            'icon-connectdevelop'=>'<i class="icon-connectdevelop"></i> Connectdevelop',
            'icon-contao'=>'<i class="icon-contao"></i> Contao',
            'icon-css3'=>'<i class="icon-css3"></i> Css3',
            'icon-dashcube'=>'<i class="icon-dashcube"></i> Dashcube',
            'icon-delicious'=>'<i class="icon-delicious"></i> Delicious',
            'icon-deviantart'=>'<i class="icon-deviantart"></i> Deviantart',
            'icon-digg'=>'<i class="icon-digg"></i> Digg',
            'icon-dribbble'=>'<i class="icon-dribbble"></i> Dribbble',
            'icon-dropbox'=>'<i class="icon-dropbox"></i> Dropbox',
            'icon-drupal'=>'<i class="icon-drupal"></i> Drupal',
            'icon-edge'=>'<i class="icon-edge"></i> Edge',
            'icon-eercast'=>'<i class="icon-eercast"></i> Eercast',
            'icon-empire'=>'<i class="icon-empire"></i> Empire',
            'icon-envira'=>'<i class="icon-envira"></i> Envira',
            'icon-etsy'=>'<i class="icon-etsy"></i> Etsy',
            'icon-expeditedssl'=>'<i class="icon-expeditedssl"></i> Expeditedssl',
            'icon-facebook'=>'<i class="icon-facebook"></i> Facebook',
            'icon-facebook-official'=>'<i class="icon-facebook-official"></i> Facebook Official',
            'icon-facebook-square'=>'<i class="icon-facebook-square"></i> Facebook Square',
            'icon-firefox'=>'<i class="icon-firefox"></i> Firefox',
            'icon-first-order'=>'<i class="icon-first-order"></i> First Order',
            'icon-flickr'=>'<i class="icon-flickr"></i> Flickr',
            'icon-font-awesome'=>'<i class="icon-font-awesome"></i> Font Awesome',
            'icon-fonticons'=>'<i class="icon-fonticons"></i> Fonticons',
            'icon-fort-awesome'=>'<i class="icon-fort-awesome"></i> Fort Awesome',
            'icon-forumbee'=>'<i class="icon-forumbee"></i> Forumbee',
            'icon-foursquare'=>'<i class="icon-foursquare"></i> Foursquare',
            'icon-free-code-camp'=>'<i class="icon-free-code-camp"></i> Free Code Camp',
            'icon-get-pocket'=>'<i class="icon-get-pocket"></i> Get Pocket',
            'icon-gg'=>'<i class="icon-gg"></i> Gg',
            'icon-gg-circle'=>'<i class="icon-gg-circle"></i> Gg Circle',
            'icon-git'=>'<i class="icon-git"></i> Git',
            'icon-git-square'=>'<i class="icon-git-square"></i> Git Square',
            'icon-github'=>'<i class="icon-github"></i> Github',
            'icon-github-alt'=>'<i class="icon-github-alt"></i> Github Alt',
            'icon-github-square'=>'<i class="icon-github-square"></i> Github Square',
            'icon-gitlab'=>'<i class="icon-gitlab"></i> Gitlab',
            'icon-glide'=>'<i class="icon-glide"></i> Glide',
            'icon-glide-g'=>'<i class="icon-glide-g"></i> Glide G',
            'icon-google'=>'<i class="icon-google"></i> Google',
            'icon-google-plus'=>'<i class="icon-google-plus"></i> Google Plus',
            'icon-google-plus-official'=>'<i class="icon-google-plus-official"></i> Google Plus Official',
            'icon-google-plus-square'=>'<i class="icon-google-plus-square"></i> Google Plus Square',
            'icon-google-wallet'=>'<i class="icon-google-wallet"></i> Google Wallet',
            'icon-gratipay'=>'<i class="icon-gratipay"></i> Gratipay',
            'icon-grav'=>'<i class="icon-grav"></i> Grav',
            'icon-hacker-news'=>'<i class="icon-hacker-news"></i> Hacker News',
            'icon-houzz'=>'<i class="icon-houzz"></i> Houzz',
            'icon-html5'=>'<i class="icon-html5"></i> Html5',
            'icon-imdb'=>'<i class="icon-imdb"></i> Imdb',
            'icon-instagram'=>'<i class="icon-instagram"></i> Instagram',
            'icon-internet-explorer'=>'<i class="icon-internet-explorer"></i> Internet Explorer',
            'icon-ioxhost'=>'<i class="icon-ioxhost"></i> Ioxhost',
            'icon-joomla'=>'<i class="icon-joomla"></i> Joomla',
            'icon-jsfiddle'=>'<i class="icon-jsfiddle"></i> Jsfiddle',
            'icon-lastfm'=>'<i class="icon-lastfm"></i> Lastfm',
            'icon-lastfm-square'=>'<i class="icon-lastfm-square"></i> Lastfm Square',
            'icon-leanpub'=>'<i class="icon-leanpub"></i> Leanpub',
            'icon-linkedin'=>'<i class="icon-linkedin"></i> Linkedin',
            'icon-linkedin-square'=>'<i class="icon-linkedin-square"></i> Linkedin Square',
            'icon-linode'=>'<i class="icon-linode"></i> Linode',
            'icon-linux'=>'<i class="icon-linux"></i> Linux',
            'icon-maxcdn'=>'<i class="icon-maxcdn"></i> Maxcdn',
            'icon-meanpath'=>'<i class="icon-meanpath"></i> Meanpath',
            'icon-medium'=>'<i class="icon-medium"></i> Medium',
            'icon-meetup'=>'<i class="icon-meetup"></i> Meetup',
            'icon-mixcloud'=>'<i class="icon-mixcloud"></i> Mixcloud',
            'icon-modx'=>'<i class="icon-modx"></i> Modx',
            'icon-odnoklassniki'=>'<i class="icon-odnoklassniki"></i> Odnoklassniki',
            'icon-odnoklassniki-square'=>'<i class="icon-odnoklassniki-square"></i> Odnoklassniki Square',
            'icon-opencart'=>'<i class="icon-opencart"></i> Opencart',
            'icon-openid'=>'<i class="icon-openid"></i> Openid',
            'icon-opera'=>'<i class="icon-opera"></i> Opera',
            'icon-optin-monster'=>'<i class="icon-optin-monster"></i> Optin Monster',
            'icon-pagelines'=>'<i class="icon-pagelines"></i> Pagelines',
            'icon-paypal'=>'<i class="icon-paypal"></i> Paypal',
            'icon-pied-piper'=>'<i class="icon-pied-piper"></i> Pied Piper',
            'icon-pied-piper-alt'=>'<i class="icon-pied-piper-alt"></i> Pied Piper Alt',
            'icon-pied-piper-pp'=>'<i class="icon-pied-piper-pp"></i> Pied Piper Pp',
            'icon-pinterest'=>'<i class="icon-pinterest"></i> Pinterest',
            'icon-pinterest-p'=>'<i class="icon-pinterest-p"></i> Pinterest P',
            'icon-pinterest-square'=>'<i class="icon-pinterest-square"></i> Pinterest Square',
            'icon-product-hunt'=>'<i class="icon-product-hunt"></i> Product Hunt',
            'icon-qq'=>'<i class="icon-qq"></i> Qq',
            'icon-quora'=>'<i class="icon-quora"></i> Quora',
            'icon-ravelry'=>'<i class="icon-ravelry"></i> Ravelry',
            'icon-rebel'=>'<i class="icon-rebel"></i> Rebel',
            'icon-reddit'=>'<i class="icon-reddit"></i> Reddit',
            'icon-reddit-alien'=>'<i class="icon-reddit-alien"></i> Reddit Alien',
            'icon-reddit-square'=>'<i class="icon-reddit-square"></i> Reddit Square',
            'icon-renren'=>'<i class="icon-renren"></i> Renren',
            'icon-safari'=>'<i class="icon-safari"></i> Safari',
            'icon-scribd'=>'<i class="icon-scribd"></i> Scribd',
            'icon-sellsy'=>'<i class="icon-sellsy"></i> Sellsy',
            'icon-share-alt'=>'<i class="icon-share-alt"></i> Share Alt',
            'icon-share-alt-square'=>'<i class="icon-share-alt-square"></i> Share Alt Square',
            'icon-shirtsinbulk'=>'<i class="icon-shirtsinbulk"></i> Shirtsinbulk',
            'icon-simplybuilt'=>'<i class="icon-simplybuilt"></i> Simplybuilt',
            'icon-skyatlas'=>'<i class="icon-skyatlas"></i> Skyatlas',
            'icon-skype'=>'<i class="icon-skype"></i> Skype',
            'icon-slack'=>'<i class="icon-slack"></i> Slack',
            'icon-slideshare'=>'<i class="icon-slideshare"></i> Slideshare',
            'icon-snapchat'=>'<i class="icon-snapchat"></i> Snapchat',
            'icon-snapchat-ghost'=>'<i class="icon-snapchat-ghost"></i> Snapchat Ghost',
            'icon-snapchat-square'=>'<i class="icon-snapchat-square"></i> Snapchat Square',
            'icon-soundcloud'=>'<i class="icon-soundcloud"></i> Soundcloud',
            'icon-spotify'=>'<i class="icon-spotify"></i> Spotify',
            'icon-stack-exchange'=>'<i class="icon-stack-exchange"></i> Stack Exchange',
            'icon-stack-overflow'=>'<i class="icon-stack-overflow"></i> Stack Overflow',
            'icon-steam'=>'<i class="icon-steam"></i> Steam',
            'icon-steam-square'=>'<i class="icon-steam-square"></i> Steam Square',
            'icon-stumbleupon'=>'<i class="icon-stumbleupon"></i> Stumbleupon',
            'icon-stumbleupon-circle'=>'<i class="icon-stumbleupon-circle"></i> Stumbleupon Circle',
            'icon-superpowers'=>'<i class="icon-superpowers"></i> Superpowers',
            'icon-telegram'=>'<i class="icon-telegram"></i> Telegram',
            'icon-tencent-weibo'=>'<i class="icon-tencent-weibo"></i> Tencent Weibo',
            'icon-themeisle'=>'<i class="icon-themeisle"></i> Themeisle',
            'icon-trello'=>'<i class="icon-trello"></i> Trello',
            'icon-tripadvisor'=>'<i class="icon-tripadvisor"></i> Tripadvisor',
            'icon-tumblr'=>'<i class="icon-tumblr"></i> Tumblr',
            'icon-tumblr-square'=>'<i class="icon-tumblr-square"></i> Tumblr Square',
            'icon-twitch'=>'<i class="icon-twitch"></i> Twitch',
            'icon-twitter'=>'<i class="icon-twitter"></i> Twitter',
            'icon-twitter-square'=>'<i class="icon-twitter-square"></i> Twitter Square',
            'icon-usb'=>'<i class="icon-usb"></i> Usb',
            'icon-viacoin'=>'<i class="icon-viacoin"></i> Viacoin',
            'icon-viadeo'=>'<i class="icon-viadeo"></i> Viadeo',
            'icon-viadeo-square'=>'<i class="icon-viadeo-square"></i> Viadeo Square',
            'icon-vimeo'=>'<i class="icon-vimeo"></i> Vimeo',
            'icon-vimeo-square'=>'<i class="icon-vimeo-square"></i> Vimeo Square',
            'icon-vine'=>'<i class="icon-vine"></i> Vine',
            'icon-vk'=>'<i class="icon-vk"></i> Vk',
            'icon-weibo'=>'<i class="icon-weibo"></i> Weibo',
            'icon-weixin'=>'<i class="icon-weixin"></i> Weixin',
            'icon-whatsapp'=>'<i class="icon-whatsapp"></i> Whatsapp',
            'icon-wikipedia-w'=>'<i class="icon-wikipedia-w"></i> Wikipedia W',
            'icon-windows'=>'<i class="icon-windows"></i> Windows',
            'icon-wordpress'=>'<i class="icon-wordpress"></i> Wordpress',
            'icon-wpbeginner'=>'<i class="icon-wpbeginner"></i> Wpbeginner',
            'icon-wpexplorer'=>'<i class="icon-wpexplorer"></i> Wpexplorer',
            'icon-wpforms'=>'<i class="icon-wpforms"></i> Wpforms',
            'icon-xing'=>'<i class="icon-xing"></i> Xing',
            'icon-xing-square'=>'<i class="icon-xing-square"></i> Xing Square',
            'icon-y-combinator'=>'<i class="icon-y-combinator"></i> Y Combinator',
            'icon-yahoo'=>'<i class="icon-yahoo"></i> Yahoo',
            'icon-yelp'=>'<i class="icon-yelp"></i> Yelp',
            'icon-yoast'=>'<i class="icon-yoast"></i> Yoast',
            'icon-youtube'=>'<i class="icon-youtube"></i> Youtube',
            'icon-youtube-play'=>'<i class="icon-youtube-play"></i> Youtube Play',
            'icon-youtube-square'=>'<i class="icon-youtube-square"></i> Youtube Square',
            'icon-hand-lizard-outline'=>'<i class="icon-hand-lizard-o"></i> Hand Lizard Outline',
            'icon-hand-o-down'=>'<i class="icon-hand-o-down"></i> Hand O Down',
            'icon-hand-o-left'=>'<i class="icon-hand-o-left"></i> Hand O Left',
            'icon-hand-o-right'=>'<i class="icon-hand-o-right"></i> Hand O Right',
            'icon-hand-o-up'=>'<i class="icon-hand-o-up"></i> Hand O Up',
            'icon-hand-paper-outline'=>'<i class="icon-hand-paper-o"></i> Hand Paper Outline',
            'icon-hand-peace-outline'=>'<i class="icon-hand-peace-o"></i> Hand Peace Outline',
            'icon-hand-pointer-outline'=>'<i class="icon-hand-pointer-o"></i> Hand Pointer Outline',
            'icon-hand-rock-outline'=>'<i class="icon-hand-rock-o"></i> Hand Rock Outline',
            'icon-hand-scissors-outline'=>'<i class="icon-hand-scissors-o"></i> Hand Scissors Outline',
            'icon-hand-spock-outline'=>'<i class="icon-hand-spock-o"></i> Hand Spock Outline',
            'icon-thumbs-down'=>'<i class="icon-thumbs-down"></i> Thumbs Down',
            'icon-thumbs-o-down'=>'<i class="icon-thumbs-o-down"></i> Thumbs O Down',
            'icon-thumbs-o-up'=>'<i class="icon-thumbs-o-up"></i> Thumbs O Up',
            'icon-thumbs-up'=>'<i class="icon-thumbs-up"></i> Thumbs Up',
            'icon-cc-amex'=>'<i class="icon-cc-amex"></i> Cc Amex',
            'icon-cc-diners-club'=>'<i class="icon-cc-diners-club"></i> Cc Diners Club',
            'icon-cc-discover'=>'<i class="icon-cc-discover"></i> Cc Discover',
            'icon-cc-jcb'=>'<i class="icon-cc-jcb"></i> Cc Jcb',
            'icon-cc-mastercard'=>'<i class="icon-cc-mastercard"></i> Cc Mastercard',
            'icon-cc-paypal'=>'<i class="icon-cc-paypal"></i> Cc Paypal',
            'icon-cc-stripe'=>'<i class="icon-cc-stripe"></i> Cc Stripe',
            'icon-cc-visa'=>'<i class="icon-cc-visa"></i> Cc Visa',
            'icon-credit-card'=>'<i class="icon-credit-card"></i> Credit Card',
            'icon-credit-card-alt'=>'<i class="icon-credit-card-alt"></i> Credit Card Alt',
            'icon-google-wallet'=>'<i class="icon-google-wallet"></i> Google Wallet',
            'icon-paypal'=>'<i class="icon-paypal"></i> Paypal',
            'icon-btc'=>'<i class="icon-btc"></i> Btc',
            'icon-eur'=>'<i class="icon-eur"></i> Eur',
            'icon-gbp'=>'<i class="icon-gbp"></i> Gbp',
            'icon-gg'=>'<i class="icon-gg"></i> Gg',
            'icon-gg-circle'=>'<i class="icon-gg-circle"></i> Gg Circle',
            'icon-ils'=>'<i class="icon-ils"></i> Ils',
            'icon-inr'=>'<i class="icon-inr"></i> Inr',
            'icon-jpy'=>'<i class="icon-jpy"></i> Jpy',
            'icon-krw'=>'<i class="icon-krw"></i> Krw',
            'icon-money'=>'<i class="icon-money"></i> Money',
            'icon-rub'=>'<i class="icon-rub"></i> Rub',
            'icon-try'=>'<i class="icon-try"></i> Try',
            'icon-usd'=>'<i class="icon-usd"></i> Usd',
            'icon-american-sign-language-interpreting'=>'<i class="icon-american-sign-language-interpreting"></i> American Sign Language Interpreting',
            'icon-assistive-listening-systems'=>'<i class="icon-assistive-listening-systems"></i> Assistive Listening Systems',
            'icon-audio-description'=>'<i class="icon-audio-description"></i> Audio Description',
            'icon-blind'=>'<i class="icon-blind"></i> Blind',
            'icon-braille'=>'<i class="icon-braille"></i> Braille',
            'icon-cc'=>'<i class="icon-cc"></i> Cc',
            'icon-deaf'=>'<i class="icon-deaf"></i> Deaf',
            'icon-low-vision'=>'<i class="icon-low-vision"></i> Low Vision',
            'icon-question-circle-outline'=>'<i class="icon-question-circle-o"></i> Question Circle Outline',
            'icon-sign-language'=>'<i class="icon-sign-language"></i> Sign Language',
            'icon-tty'=>'<i class="icon-tty"></i> Tty',
            'icon-universal-access'=>'<i class="icon-universal-access"></i> Universal Access',
            'icon-volume-control-phone'=>'<i class="icon-volume-control-phone"></i> Volume Control Phone',
            'icon-wheelchair'=>'<i class="icon-wheelchair"></i> Wheelchair',
            'icon-wheelchair-alt'=>'<i class="icon-wheelchair-alt"></i> Wheelchair Alt',
            'icon-genderless'=>'<i class="icon-genderless"></i> Genderless',
            'icon-mars'=>'<i class="icon-mars"></i> Mars',
            'icon-mars-double'=>'<i class="icon-mars-double"></i> Mars Double',
            'icon-mars-stroke'=>'<i class="icon-mars-stroke"></i> Mars Stroke',
            'icon-mars-stroke-h'=>'<i class="icon-mars-stroke-h"></i> Mars Stroke H',
            'icon-mars-stroke-v'=>'<i class="icon-mars-stroke-v"></i> Mars Stroke V',
            'icon-mercury'=>'<i class="icon-mercury"></i> Mercury',
            'icon-neuter'=>'<i class="icon-neuter"></i> Neuter',
            'icon-transgender'=>'<i class="icon-transgender"></i> Transgender',
            'icon-transgender-alt'=>'<i class="icon-transgender-alt"></i> Transgender Alt',
            'icon-venus'=>'<i class="icon-venus"></i> Venus',
            'icon-venus-double'=>'<i class="icon-venus-double"></i> Venus Double',
            'icon-venus-mars'=>'<i class="icon-venus-mars"></i> Venus Mars',
        ];
    }
}
